"""Add publishing tables

Revision ID: f9b7296a76f2
Revises: b1ed6dd977b0
Create Date: 2020-10-08 17:00:21.410249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9b7296a76f2'
down_revision = 'b1ed6dd977b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('metadata_status',
                    sa.Column('metadata_id', sa.String(), nullable=False),
                    sa.Column('catalogue_record', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.Column('published', sa.Boolean(), nullable=False),
                    sa.Column('created', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('updated', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('checked', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('metadata_id')
                    )
    op.create_index('ix_metadata_status_created_metadata_id', 'metadata_status', ['created', 'metadata_id'],
                    unique=False)
    op.create_table('datacite_status',
                    sa.Column('metadata_id', sa.String(), nullable=False),
                    sa.Column('doi', sa.String(), nullable=True),
                    sa.Column('datacite_record', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('published', sa.Boolean(), nullable=False),
                    sa.Column('updated', sa.TIMESTAMP(timezone=True), nullable=True),
                    sa.Column('checked', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('error', sa.String(), nullable=True),
                    sa.Column('retries', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['metadata_id'], ['metadata_status.metadata_id'], ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('metadata_id'),
                    sa.UniqueConstraint('doi')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table('datacite_status')
    op.drop_index('ix_metadata_status_created_metadata_id', table_name='metadata_status')
    op.drop_table('metadata_status')
    # ### end Alembic commands ###
