"""Add role admin flag

Revision ID: b1ed6dd977b0
Revises: f11e224a11f5
Create Date: 2020-07-14 11:00:41.522744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ed6dd977b0'
down_revision = 'f11e224a11f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted to set defaults ###
    op.add_column('role', sa.Column('admin', sa.Boolean(), nullable=True))
    op.execute("UPDATE role SET admin = false")
    op.execute("UPDATE role SET admin = true WHERE key IN ('admin', 'curator')")
    op.alter_column('role', 'admin', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column('role', 'admin')
    # ### end Alembic commands ###
