"""Add publishing tables

Revision ID: 087581f76d96
Revises: c967263958b7
Create Date: 2020-09-22 12:19:03.279507

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '087581f76d96'
down_revision = 'c967263958b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('metadata_status',
                    sa.Column('metadata_id', sa.String(), nullable=False),
                    sa.Column('catalogue_record', sa.JSON(), nullable=False),
                    sa.Column('published', sa.Boolean(), nullable=False),
                    sa.Column('updated', sa.DateTime(), nullable=False),
                    sa.Column('checked', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('metadata_id')
                    )
    op.create_table('datacite_status',
                    sa.Column('published', sa.Boolean(), nullable=False),
                    sa.Column('updated', sa.DateTime(), nullable=True),
                    sa.Column('checked', sa.DateTime(), nullable=False),
                    sa.Column('error', sa.String(), nullable=True),
                    sa.Column('retries', sa.Integer(), nullable=True),
                    sa.Column('doi', sa.String(), nullable=True),
                    sa.Column('datacite_record', sa.JSON(), nullable=True),
                    sa.Column('metadata_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['metadata_id'], ['metadata_status.metadata_id'], ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('metadata_id'),
                    sa.UniqueConstraint('doi')
                    )
    op.create_table('elasticsearch_status',
                    sa.Column('published', sa.Boolean(), nullable=False),
                    sa.Column('updated', sa.DateTime(), nullable=True),
                    sa.Column('checked', sa.DateTime(), nullable=False),
                    sa.Column('error', sa.String(), nullable=True),
                    sa.Column('retries', sa.Integer(), nullable=True),
                    sa.Column('index', sa.String(), nullable=True),
                    sa.Column('metadata_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['metadata_id'], ['metadata_status.metadata_id'], ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('metadata_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table('elasticsearch_status')
    op.drop_table('datacite_status')
    op.drop_table('metadata_status')
    # ### end Alembic commands ###
