"""Make password nullable

Revision ID: f11e224a11f5
Revises: 
Create Date: 2020-07-07 11:29:44.736383

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f11e224a11f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.alter_column('user', 'password',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.alter_column('user', 'password',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###
