"""Make DOI mandatory wrt DataCite

Revision ID: 1e51009ae3c6
Revises: dd76ea29c361
Create Date: 2020-11-09 12:05:25.040052

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1e51009ae3c6'
down_revision = 'dd76ea29c361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.alter_column('datacite_status', 'doi',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.alter_column('datacite_status', 'doi',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###
