"""Single field for user name

Revision ID: fba3c5e8ab83
Revises: 249e24966335
Create Date: 2021-07-01 10:37:02.780672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba3c5e8ab83'
down_revision = '249e24966335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('user', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('user', 'given_name')
    op.drop_column('user', 'family_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('user', sa.Column('family_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('given_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
