"""Restructure datacite_record

Revision ID: d378fac89192
Revises: afc833d48858
Create Date: 2021-03-05 15:46:04.085533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd378fac89192'
down_revision = 'afc833d48858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.add_column('datacite_record', sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('datacite_record', sa.Column('url', sa.String(), nullable=True))
    op.create_unique_constraint('datacite_record_url_key', 'datacite_record', ['url'])
    op.drop_column('datacite_record', 'datacite_record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.add_column('datacite_record', sa.Column('datacite_record', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint('datacite_record_url_key', 'datacite_record', type_='unique')
    op.drop_column('datacite_record', 'url')
    op.drop_column('datacite_record', 'metadata_')
    # ### end Alembic commands ###
