"""Do not cascade institution delete

Revision ID: b3fca062a45e
Revises: 4c21d127611f
Create Date: 2021-02-24 12:52:44.739415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3fca062a45e'
down_revision = '4c21d127611f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_constraint('institution_parent_id_fkey', 'institution', type_='foreignkey')
    op.create_foreign_key('institution_parent_id_fkey', 'institution', 'institution', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_constraint('institution_parent_id_fkey', 'institution', type_='foreignkey')
    op.create_foreign_key('institution_parent_id_fkey', 'institution', 'institution', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
