FROM python:3.8

WORKDIR /srv

RUN git clone https://github.com/SAEONData/ODP-API.git
RUN git clone https://github.com/SAEONData/ODP-API-CKANAdapter.git
RUN git clone https://github.com/SAEONData/ODP-API-ElasticAdapter.git
RUN git clone https://github.com/SAEONData/ODP-AccountsLib.git

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN cd ODP-API && pip install -e .
RUN cd ODP-API-CKANAdapter && pip install -e .
RUN cd ODP-API-ElasticAdapter && pip install -e .
RUN cd ODP-AccountsLib && pip install -e .

ARG CA_CERT_URL
RUN curl ${CA_CERT_URL} -k -f -o /usr/local/share/ca-certificates/saeon-internal-ca.crt; exit 0
RUN update-ca-certificates

CMD ["python", "ODP-API/odpapi/main.py"]
