FROM python:3.6

WORKDIR /srv

RUN git clone https://github.com/SAEONData/ODP-Identity.git
RUN git clone https://github.com/SAEONData/ODP-AccountsLib.git
RUN git clone https://github.com/SAEONData/Hydra-Admin-Client.git
RUN git clone https://github.com/SAEONData/Hydra-OAuth2-Blueprint.git

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN cd ODP-Identity && pip install -e .
RUN cd ODP-AccountsLib && pip install -e .
RUN cd Hydra-Admin-Client && pip install -e .
RUN cd Hydra-OAuth2-Blueprint && pip install -e .

ARG CA_CERT_URL
RUN curl ${CA_CERT_URL} -k -o /usr/local/share/ca-certificates/saeon-internal-ca.crt
RUN update-ca-certificates

CMD ["gunicorn", "-b 0.0.0.0:9024", "odpidentity:create_app()"]
