FROM python:3.6

WORKDIR /srv

RUN git clone https://github.com/SAEONData/ODP-Admin.git
RUN git clone https://github.com/SAEONData/ODP-AccountsLib.git
RUN git clone https://github.com/SAEONData/Hydra-Admin-Client.git
RUN git clone https://github.com/SAEONData/Hydra-OAuth2-Blueprint.git

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN cd ODP-Admin && pip install -e .
RUN cd ODP-AccountsLib && pip install -e .
RUN cd Hydra-Admin-Client && pip install -e .
RUN cd Hydra-OAuth2-Blueprint && pip install -e .

ENV GUNICORN_CMD_ARGS --forwarded-allow-ips=*

CMD ["gunicorn", "-b 0.0.0.0:9025", "odpadmin:create_app()"]
