FROM python:3.7

WORKDIR /srv

RUN git clone https://github.com/SAEONData/ODP-AccountsAPI.git
RUN git clone https://github.com/SAEONData/ODP-AccountsLib.git
RUN git clone https://github.com/SAEONData/Hydra-Admin-Client.git

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN cd ODP-AccountsAPI && pip install .
RUN cd ODP-AccountsLib && pip install .
RUN cd Hydra-Admin-Client && pip install .

ARG CA_CERT_URL
RUN curl ${CA_CERT_URL} -k -f -o /usr/local/share/ca-certificates/saeon-internal-ca.crt; exit 0
RUN update-ca-certificates

CMD ["uvicorn", "accountsapi:app", "--host", "0.0.0.0", "--port", "9999"]
